<?php

/**
 * @file
 * Primary module hooks for My Module module.
 */

/**
 * Implements hook_help().
 */
function mymodule_demo_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.rector_demo':
      // Deprecated drupal_set_message().
      drupal_set_message(t('This is a demo help page.'));
      break;
  }
}

// Excercise 4
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {
  // print_r('==========');
  // print_r($form_id);
  // print_r('==========');

  if($form_id == 'node_article_form') {
    // Add new form element.
    $form['test_field'] = [
      '#type' => 'textfield',
      '#title' => 'Test field',
    ];
    // Alter existing element.
    $form['field_tags']['widget']['target_id']['#title'] = 'Test title';
    // Add a new submit function etc.
  }

  // Deprecated service:
  $path = drupal_get_path('module', 'mymodule');
}

// FYI hooks will be completely deprecated in future.
